version: "3.8"
services:
  whoami1:
    image: traefik/whoami
    deploy:
      replicas: 2
    labels:
      traefik.enable: true
      traefik.http.Routers.RouterMini.Rule: PathPrefix(`/whoami`)

networks:
  default:
    name: test-net
    external: true
