version: "3.8"
services:
  haproxy:
    image: haproxy:2.2
    extra_hosts:
      - traefik:host-gateway
    volumes:
      - test-config:/usr/local/etc/haproxy/
#      - ../haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  whoami:
    image: traefik/whoami

networks:
  default:
    name: test-net
    external: true

volumes:
  test-config:
    external: true
